import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { HeaderAuth } from "@/components/header-auth";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased dark"
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider>
          <header className="flex items-center justify-between px-6 py-4 border-b border-border bg-background">
            <span className="text-lg font-semibold tracking-tight">Link Shortener</span>
            <HeaderAuth />
          </header>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
